### ISSUE TITLE
Illegal castling

### ISSUE THREAD

**Issue by SzotsGabor** [lucametehau/CloverEngine#154]
I noticed that v5.0 uses e1h1 and e8h8 for short castling which Arena deems illegal because it looks like the king takes its own rook.
Other engines use e1g1 and e8g8.

Gabor Szots
CCRL

**Comment by lucametehau** [comment]
Hi Gabor!

> Edit: fixes illegal castle moves in Arena

This is from the Release page. Some weeks ago, Jorg from CEGT reported the same problem, so I fixed it, by replacing silently binaries with the fix. You probably still have binaries from first release. Could you try redownloading and testing again?

**Comment by SzotsGabor** [comment]
Hi Luca,

I've missed the fix, obviously. I have downloaded the engine again and replaced the old one. I expect it will work all right now but I'm coming back to you if something goes wrong.

Thanks!

**Comment by lucametehau** [comment]
Nice to hear! I suppose nothing went wrong :). Thanks for opening the issue
