### ISSUE TITLE
older Fathom version

### ISSUE THREAD

**Issue by jdart1** [lucametehau/CloverEngine#161]
It looks like you have incorporated Fathom code, but what you have is behind the current codebase at https://github.com/jdart1/Fathom. I suggest that you import that repo as a submodule, as Arasan does. That would make it easier to stay current with updates. It would also make clearer what the licensing for that code is, since you would have the original LICENSE file included in the submodule. By the way, I do not see that your own code has any license defined for it.

**Comment by lucametehau** [comment]
Hi Jon!

Thanks for the report, previously I just copypasted the Fathom code file by file and didn't copy the LICENSE, but I credited and I thought that was the end. Obviously it wasn't and I once again thank you for the issue. I have created a [branch](https://github.com/lucametehau/CloverEngine/tree/fathom-submodule) to add Fathom as submodule.
Could you please review and tell me if anything is missing, althought it doesn't look like? :D

**Comment by jdart1** [comment]
Doesn't look quite right. It looks like you moved the code out of the src subdirectory? I don't think you need to do that. It can be in that subdirectory with the Fathom module under it. Also, if you have modified tbconfig.h in any way, your should have a copy of it in your directory, and the Makefile should have -I. -IFathom in the compile flags, so that your tbconfig.h will be picked up instead of the one in the Fathom directory.

**Comment by lucametehau** [comment]
```                
 from main.cpp:21:
Fathom/src/tbprobe.h:27:10: fatal error: tbconfig.h: No such file or directory
   27 | #include <tbconfig.h>
      |          ^~~~~~~~~~~~
compilation terminated.
```
I have changed tbconfig.h because of this, is this normal?

**Comment by jdart1** [comment]
To fix this, you need to compile Fathom code with a proper include path. I recommend having a copy of tbconfig.h in your own source directory. That will allow you for example to modify it to use your own POPCNT implementation. You could also have it use your own attack generation code. Then, when you compile the code, set -I . in your Makefile.  That will pick up your own tbconfig.h and use it.

**Comment by jdart1** [comment]
Don't modify tbconfig.h in the Fathom directory: the idea is that directory maintains sync to the repo it references.

**Comment by lucametehau** [comment]
Alright, new [branch](https://github.com/lucametehau/CloverEngine/tree/fathom) with all fixes. Anything missing now? :)

**Comment by jdart1** [comment]
Looks ok to me now.

**Comment by lucametehau** [comment]
Alright, thanks a lot for the PR and the guidance! Good luck with Arasan! :)
