### ISSUE TITLE
Disconnecting during the build?

### ISSUE THREAD

**Issue by N1ghtey** [lucametehau/CloverEngine#205]
Hey! I stumbled upon this issue, and it happened only trying to build your engine...

```
Cloning into 'CloverEngine'...
remote: Enumerating objects: 4011, done.
remote: Counting objects: 100% (396/396), done.
remote: Compressing objects: 100% (180/180), done.
error: 6892 bytes of body are still expectedB | 254.00 KiB/s 
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output

```

**Comment by lucametehau** [comment]
Hey! Really weird, never seen this. Can you try cloning with ``--depth 1`` and see if it works?

**Comment by N1ghtey** [comment]
So... Apparently there is some bug with git clone, I even rebooted the machine and didn't solve it, so I tried using a network from my phone which is way slower, but fixed the issue? even checking the firewall setting nor enabling/disabling it solved.
But yeah, it seems now to be fine! Smh.

**Comment by N1ghtey** [comment]
Build successful!

**Comment by lucametehau** [comment]
With ``--depth 1`` option? Clover without that option is like 1Gb size for some reason... that might be way git disconnects.

**Comment by N1ghtey** [comment]
without it, yes. Beta.nnue... the right network?

**Comment by N1ghtey** [comment]
1.4 GiB (On linux)

**Comment by lucametehau** [comment]
> without it, yes. Beta.nnue... the right network?

Yep, also sorry for the big size, idk how to fix it
