### ISSUE TITLE
syzygy

### ISSUE THREAD

**Issue by Jubilao3** [lucametehau/CloverEngine#282]
Thanks for Clover. I like it a lot and I'm trying it out on PlayChess.com. Its style is great, and it's fast. I don't usually use syzygy anymore because the engines have plenty of knowledge of the endgames. But I tried syzygy with Clover and it lost the game because the nodes per second dropped too much, and it got checkmated. I removed syzygy and the rest of the games were great!
[Clover games.zip](https://github.com/user-attachments/files/16843384/Clover.games.zip)

**Comment by lucametehau** [comment]
Hey there! Thank you for using Clover, much appreciated! :)

Issues like this with Syzygy often appear because Syzygy is stored on an HDD and not an SSD. Mind sharing what you keep your Syzygy on?

**Comment by Jubilao3** [comment]
It is true that the disk that contains the syzygy is not SSD. This does not pose any problem for Stockfish and its clones.

**Comment by Jubilao3** [comment]
I totally agree, it is better not to use syzygy. Thanks.
