### ISSUE TITLE
Logo proposal

### ISSUE THREAD

**Issue by PabloDaniel0** [lucametehau/CloverEngine#32]
i realized that the engine has no logo so i have designed one for it. the logo can be used as the official clover chess engine logo
![clover](https://user-images.githubusercontent.com/82627806/151066520-8b480ab1-56c6-4037-bc6a-42d0a56f1c69.jpg)
![Clover](https://user-images.githubusercontent.com/82627806/151066524-36b8c0c6-f5d6-40df-91a3-223eb060d8b9.png)
![clover (100 x 50)](https://user-images.githubusercontent.com/82627806/151066526-b56e2dfc-962d-44b0-80d4-633fa7553c93.jpg)
![Clover logo in arena](https://user-images.githubusercontent.com/82627806/151066855-69a5df98-b8ca-4156-98d7-7f352aad63ed.png)

.

**Comment by lucametehau** [comment]
Hi Daniel! Thanks for taking your time to do this, it looks really nice :) ! You can open a pull request and I'll merge it as soon as I can.
