### ISSUE TITLE
Clover 3.1 compilation

### ISSUE THREAD

**Issue by microsmeta** [lucametehau/CloverEngine#36]
Hi Luca!
I'm a Clover fan! 
Could you please compile it also for macOS M1 NEON or give me a modified makefile for doing that on my Mac M1?
I've tryed for myself to add it to my Mac TOP engines tournament, buts unsuccesfully. With + 200 ELO is a TOP!!!!

http://talkchess.com/forum3/viewtopic.php?f=2&t=75911

I know that Clover 3.0 is compatible with ARM64, since Archimedes has compiled it also for Android.

HERE THE ANDROID BUILD:  https://pixeldrain.com/u/UysEtSqZ

Kind regards, Alex

**Comment by lucametehau** [comment]
Hi Alex!

Thanks for trying out Clover!
I have no experience whatsoever with any mac related thing, so sadly I can't be of much help in this case.
I suppose there shouldn't be any major difference in the makefile (if no difference at all) to make it work for macOS.
I'll keep this issue open and in case you find something, don't hesitate to share!

Regards,
Luca

**Comment by Disservin** [comment]
Since Mac doesnt support march=native and gives me many errors because of the intrinsics you (or the maintainer) could replace them with non intrinsic functions which will definitely slow the program down... but changing the makefile wont do it (I believe)

**Comment by microsmeta** [comment]
Thank you I try :-)

Il giorno sab 2 apr 2022 alle ore 22:49 disservin ***@***.***>
ha scritto:

**Comment by lucametehau** [comment]
> Since Mac doesnt support march=native and gives me many errors because of the intrinsics you (or the maintainer) could replace them with non intrinsic functions which will definitely slow the program down... but changing the makefile wont do it (I believe)

That's something I'm working on: doing something for non-avx2 users. I'll have to study...

**Comment by microsmeta** [comment]
Yes please, I'm learning too, modding Stockfish and compiling all engines
for Mac M1, Android and Windows 11 ARM64 (only Popcnt sse41)

If you manage to modify your makefile for Apple Silicon M1, gcc NEON,I can
compile Clover 3.1 for Mac for you, so you can add also it to your
repository 😀

https://www.chess.com/forum/view/game-analysis/freeware-against-commercial-chess-software-arena-3-5-1-vs-chessbase-fritz-17?page=1

Il giorno dom 3 apr 2022 alle ore 13:23 lucametehau <
***@***.***> ha scritto:

**Comment by lucametehau** [comment]
You can now locally compile and it will create 3 binaries out of which 1 surely works for your PC.

**Comment by microsmeta** [comment]
Thank you! Happy that you continue to develop Clover 😊

Il giorno lun 20 feb 2023 alle ore 18:03 lucametehau <
***@***.***> ha scritto:
