### ISSUE TITLE
Invite Clover to participate in a chess engine tournament and new version of logo

### ISSUE THREAD

**Issue by PabloDaniel0** [lucametehau/CloverEngine#38]
Hello again! you may remember me for having designed the logo for Clover, this time I would like to invite Clover to participate in an engine tournament I am organizing, it is called OSCET _(Open Source Chess Engine Tournament)_, the goal of the tournament is for the strongest open source engines to compete in the tournament, to highlight its importance the details are here:
https://sites.google.com/view/oscet/take-part
Registration form:
https://forms.gle/xE51X3S7bkuCQihB6
Discord:
https://discord.com/invite/e8H5QfdttV
Before I say goodbye I share a square version of the logo I designed before for Gui's like Banksia that allow this kind of logos and look better in Banksia
![Clover_Logo_Square_Transparent](https://user-images.githubusercontent.com/82627806/165672627-7bebabca-a506-4cea-966a-c69d1d4c0265.png)
![Clover_Logo_Square](https://user-images.githubusercontent.com/82627806/165672628-af8bbac9-a574-4086-ad27-870bec11df9e.jpg)

**Comment by lucametehau** [comment]
Hello again!

Thanks for the invitation! It looks like a though tournament and Clover is the last rating-wise, but I'll accept as it's nice to see other people using and testing Clover. I'll soon complete the form. As for the logo, you can do as the last time, just open a pull request and I'll merge it.

Regards,
Luca

**Comment by lucametehau** [comment]
I have registered, hope you got my form. I will close this issue now! And don't forget to open up a pull request if you want for the logo!
