### ISSUE TITLE
"Segmentation fault (core dumped)" under linux

### ISSUE THREAD

**Issue by emdio** [lucametehau/CloverEngine#4]
I compiled the code with make under linux, with no issue at all.

I got five Clover executable, all of them crash one way or another.

The ones that make it to the "go" command send a "Segmentation fault (core dumped)" message.

$ ./Clover.2.3.exe 
Clover 2.3 by Luca Metehau
ucinewgame
go
Segmentation fault (core dumped)

PS: I tried running these from the command line after the engine crashing under scid-vs-pc

**Comment by lucametehau** [comment]
Hello emdio,

I think this is because of the static flags. Try removing them from the makefile and see if it works. If this is the problem, I will somwhow solve this or add a note in the README.md.

**Comment by emdio** [comment]
Nice! Removing the static flags solved the issue.
