### ISSUE TITLE
Release binary of Clover 3.2 isn't compatible with every Avx2 cpu

### ISSUE THREAD

**Issue by PGG106** [lucametehau/CloverEngine#43]
Hi, just an heads up, i tried running the release binary of clover 3.2 on an i7 8700k, while it supports avx2 it still wasn't able to run the supposedly avx2 release, building from source works just fine so you might have used -march=native by mistake.

**Comment by lucametehau** [comment]
Hi, thank you for letting me know! It's not an avx2 problem, it's rather a problem with the exe. I'll try fixing it asap

**Comment by PGG106** [comment]
my best guess is you compiling for an architecture my cpu isn't compatible with (ie: march-native with a cpu newer than mine), i'll happily test any other binary, also good job on the engine, it's almost too strong xd

**Comment by lucametehau** [comment]
After further inspection, it seems that there is UB with the non-native build. Hell, I can't even debug it, when I add the -g flag it all works magically. This will most likely take some time to debug. In the mean time, best you can do is download the code and run ``make run``.

**Comment by lucametehau** [comment]
Alright, updated exe, should be working fine I guess? Let me know if you can't run it =)

**Comment by PGG106** [comment]
I can confirm the binary works correctly and has the same bench as my native compiled one.
